apiVersion: "nais.io/v1alpha1"
kind: "Alert"
metadata:
  name: ditt-nav-arbeidsgiver-api-alert
  labels:
    team: arbeidsgiver
spec:
  receivers:
    slack:
      channel: 'arbeidsgiver-notifications'
      prependText: '<!here> | '
  alerts:
    - alert: applikasjon nede
      expr: count(kube_pod_container_status_running{container="ditt-nav-arbeidsgiver-api"}) == 0
      for: 2m
      description: "ditt-nav-arbeidsgiver er nede i prod"
      action: "finn podden i kubectl og undersøk loggene for å finne feilen"