apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: demo-min-side-arbeidsgiver-api
  namespace: fager
  labels:
    team: fager
spec:
  image: {{{image}}}
  replicas:
    min: 1
    max: 1
  liveness:
    path: /ditt-nav-arbeidsgiver-api/internal/actuator/health
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /ditt-nav-arbeidsgiver-api/internal/actuator/health
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  resources:
    limits:
      cpu: 2000m
      memory: 3000Mi
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: demo
  prometheus:
    enabled: true
    path: /ditt-nav-arbeidsgiver-api/internal/actuator/prometheus
  accessPolicy:
    inbound:
      rules:
        - application: demo-min-side-arbeidsgiver
        - application: demo-min-side-arbeidsgiver-experimental
    outbound:
      rules:
        - application: arbeidsgiver-fake-login
