apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: min-side-arbeidsgiver-api
  namespace: fager
  labels:
    team: fager
spec:
  image: {{{ image }}}
  liveness:
    path: /ditt-nav-arbeidsgiver-api/internal/actuator/health
    initialDelay: 90
    timeout: 15
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /ditt-nav-arbeidsgiver-api/internal/actuator/health
    initialDelay: 90
    timeout: 15
    periodSeconds: 10
    failureThreshold: 3
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "altinn:serviceowner/rolesandrights"
        - name: "altinn:serviceowner/organizations"
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: min-side-arbeidsgiver-api
            envVarPrefix: DB
  envFrom:
    - secret: min-side-ag-secrets
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
  prometheus:
    enabled: true
    path: /ditt-nav-arbeidsgiver-api/internal/actuator/prometheus
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: min-side-arbeidsgiver
    outbound:
      rules:
        - application: altinn-rettigheter-proxy
          namespace: arbeidsgiver
      external:
        - host: api-gw-q1.oera.no
        - host: ereg-services.dev-fss-pub.nais.io
