apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: min-side-arbeidsgiver-api
  namespace: fager
  labels:
    team: fager
spec:
  image: {{{ image }}}
  #replicas:
  #  min: 0
  #  max: 0
  liveness:
    path: /ditt-nav-arbeidsgiver-api/internal/actuator/health
  readiness:
    path: /ditt-nav-arbeidsgiver-api/internal/actuator/health
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "altinn:serviceowner/rolesandrights"
        - name: "altinn:serviceowner/organizations"
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_13
        databases:
          - name: min-side-arbeidsgiver-api
            envVarPrefix: DB
  envFrom:
    - secret: min-side-ag-secrets
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: JAVA_OPTS
      value: "-XX:+UseParallelGC -XX:MaxRAMPercentage=75.0 -XX:ActiveProcessorCount=2"
  prometheus:
    enabled: true
    path: /ditt-nav-arbeidsgiver-api/internal/actuator/prometheus
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: min-side-arbeidsgiver
    outbound:
      rules:
        - application: altinn-rettigheter-proxy
          namespace: arbeidsgiver
      external:
        - host: tt02.altinn.no
        - host: api-gw-q1.oera.no
        - host: ereg-services.dev-fss-pub.nais.io
        - host: sokos-kontoregister-q2.dev-fss-pub.nais.io
