apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: min-side-arbeidsgiver-api
  namespace: fager
  labels:
    team: fager
spec:
  image: {{{ image }}}
  liveness:
    path: /internal/isalive
  readiness:
    path: /internal/isready
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "altinn:serviceowner/rolesandrights"
        - name: "altinn:serviceowner/organizations"
        - name: "altinn:serviceowner/delegationrequests.read"
        - name: "altinn:serviceowner/delegationrequests.write"
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-f1-micro
        databases:
          - name: min-side-arbeidsgiver-api
            envVarPrefix: DB
  envFrom:
    - secret: min-side-ag-secrets
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: min-side-arbeidsgiver
    outbound:
      rules:
        - application: arbeidsgiver-altinn-tilganger
      external:
        - host: tt02.altinn.no
        - host: api-gw-q1.oera.no
        - host: ereg-services.dev-fss-pub.nais.io
        - host: sokos-kontoregister-q2.dev-fss-pub.nais.io
