apiVersion: nais.io/v1alpha1
kind: "Application"
metadata:
  name: ditt-nav-arbeidsgiver-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /ditt-nav-arbeidsgiver-api/internal/actuator/health
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /ditt-nav-arbeidsgiver-api/internal/actuator/health
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  resources:
    limits:
      cpu: 2000m
      memory: 3000Mi
    requests:
      cpu: 500m
      memory: 600Mi
  ingresses:
    - https://arbeidsgiver.labs.nais.io/ditt-nav-arbeidsgiver-api/
  webproxy: false
  vault:
    enabled: false
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: labs
  prometheus:
    enabled: true
    path: /ditt-nav-arbeidsgiver-api/internal/actuator/prometheus
  accessPolicy:
    inbound:
      rules:
        - application: ditt-nav-arbeidsgiver
    outbound:
      rules:
        - application: min-side-ag-fakelogin