apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: min-side-arbeidsgiver-api
  namespace: fager
  labels:
    team: fager
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/fager/min-side-arbeidsgiver-api:687b1a24ace97af7eb667a694bf3056332c5b4af
  resources:
    requests:
      cpu: 400m
      memory: 512Mi
    limits:
      cpu: 5000m # https://home.robusta.dev/blog/stop-using-cpu-limits/
      memory: 1024Mi
  replicas:
    max: 0
    min: 0
  liveness:
    path: /ditt-nav-arbeidsgiver-api/internal/actuator/health
    initialDelay: 90
    timeout: 15
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /ditt-nav-arbeidsgiver-api/internal/actuator/health
    initialDelay: 90
    timeout: 15
    periodSeconds: 10
    failureThreshold: 3
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "altinn:serviceowner/rolesandrights"
        - name: "altinn:serviceowner/organizations"
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-custom-1-3840
        databases:
          - name: min-side-arbeidsgiver-api
            envVarPrefix: DB
  envFrom:
    - secret: min-side-ag-secrets
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod-gcp
    - name: JAVA_OPTS
      value: "-XX:+UseParallelGC -XX:MaxRAMPercentage=75.0 -XX:ActiveProcessorCount=2"
  prometheus:
    enabled: true
    path: /ditt-nav-arbeidsgiver-api/internal/actuator/prometheus
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: min-side-arbeidsgiver
    outbound:
      rules:
        - application: altinn-rettigheter-proxy
          namespace: arbeidsgiver
      external:
        - host: www.altinn.no
        - host: api-gw.oera.no
        - host: ereg-services.prod-fss-pub.nais.io
        - host: sokos-kontoregister.prod-fss-pub.nais.io
