apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: min-side-arbeidsgiver-api
  namespace: fager
  labels:
    team: fager
spec:
  image: {{{image}}}
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 5000m # https://home.robusta.dev/blog/stop-using-cpu-limits/
      memory: 1024Mi
  liveness:
    path: /internal/isalive
  readiness:
    path: /internal/isready
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "altinn:serviceowner/rolesandrights"
        - name: "altinn:serviceowner/organizations"
        - name: "altinn:serviceowner/delegationrequests.read"
        - name: "altinn:serviceowner/delegationrequests.write"
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-custom-1-3840
        databases:
          - name: min-side-arbeidsgiver-api
            envVarPrefix: DB
  envFrom:
    - secret: min-side-ag-secrets
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: min-side-arbeidsgiver
    outbound:
      rules:
        - application: arbeidsgiver-altinn-tilganger
      external:
        - host: www.altinn.no
        - host: api-gw.oera.no
        - host: ereg-services.prod-fss-pub.nais.io
        - host: sokos-kontoregister.prod-fss-pub.nais.io
