name: Deploy dev
on:
  workflow_dispatch:

jobs:
  deploy-dev-gcp:
    name: Deploy dev (dev-gcp)
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - uses: nais/login@v0
        id: login
        with:
          team: fager
      - uses: nais/deploy/actions/deploy@v2
        env:
          VAR: image=${{ steps.login.outputs.registry }}/min-side-arbeidsgiver-api:${{ github.sha }}
          RESOURCE: nais/dev-env.yaml
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
