name: deploy kafka topic

on:
  push:
    branches: ['main']
    paths: ['config/nais-kafka-topic.yaml']
  workflow_dispatch:

jobs:
  deploy-dev:
    name: Deploy kafka
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: config/nais-kafka-topic.yaml
          PRINT_PAYLOAD: true
          VAR: pool=nav-dev

      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: config/nais-kafka-topic.yaml
          PRINT_PAYLOAD: true
          VAR: pool=nav-prod
